apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  # When you're using minikube context, this image will be pushed to your local
  # docker daemon. If you're using a non-minikube context, the image will be
  # pushed to a private quay.io repository.
  - image: quay.io/newrelic/infrastructure-k8s-dev
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        TARGETOS: linux
        TARGETARCH: amd64
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - deploy/local.yaml
profiles:
- name: unprivileged
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    # When you're using minikube context, this image will be pushed to your local
    # docker daemon. If you're using a non-minikube context, the image will be
    # pushed to a private quay.io repository.
    - image: quay.io/newrelic/infrastructure-k8s-dev
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          MODE: unprivileged
    local: {}
  deploy:
    kubectl:
      manifests:
        - deploy/local-unprivileged.yaml
- name: openshift
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - image: default-route-openshift-image-registry.apps-crc.testing/default/infrastructure-k8s-dev
      context: .
      docker:
        dockerfile: Dockerfile
    local: {}
  deploy:
    kubectl:
      manifests:
        - deploy/local-openshift.yaml
